/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.skittishsloth.assertgen.app;

public class App {
    public static void main(String[] args) {
        
    }
}
